services:
  kafka:
    image: apache/kafka:3.7.2
    container_name: autoscaler-kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
    networks:
      - autoscaler-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s

  kafka-init:
    image: apache/kafka:3.7.2
    container_name: autoscaler-kafka-init
    depends_on:
      kafka:
        condition: service_healthy
    command: >
      bash -c '
      echo "Creating Kafka topic...";
      /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic events --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1;
      echo "Kafka topic created successfully."
      '
    networks:
      - autoscaler-network

  mongodb:
    image: mongo:8.0
    container_name: autoscaler-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - autoscaler-network
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.runCommand({ ping: 1 })' | mongosh mongodb://localhost:27017/test --quiet"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  redis:
    image: redis:7.4-alpine
    container_name: autoscaler-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    networks:
      - autoscaler-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  autoscaler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autoscaler-app
    depends_on:
      kafka-init:
        condition: service_completed_successfully
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - AUTOSCALER_CONFIG=/app/config.docker.yaml
    ports:
      - "8080:8080"
    networks:
      - autoscaler-network

volumes:
  mongodb-data:

networks:
  autoscaler-network:
    driver: bridge
